syntax = "proto3";

package ax_proto_msgs;

option go_package = "webrtc_client/proto";
option optimize_for = SPEED;

message MastState {
    message MotionState {
        enum Type {
            UNKNOWN      = 0;
            MOVING_HOLD  = 1;
            MOVING_UP    = 2;
            MOVING_DOWN  = 3;
        }
    }

    float            target_height  = 1;  // metres
    float            current_height = 2;  // metres
    MotionState.Type motion_state   = 3;
    int32            error          = 4;
    string           error_message  = 5;
}
